#!/bin/bash
# Friday Bootstrap Script
# Sets up Friday AI Assistant workspace

set -e

echo "======================================================================="
echo "  🤖 Friday Bootstrap — Setting Up Your AI Assistant"
echo "======================================================================="
echo ""

WORKSPACE="$HOME/.openclaw/workspace"

# Check if OpenClaw is installed
if ! command -v openclaw &> /dev/null; then
    echo "❌ OpenClaw not found!"
    echo ""
    echo "Install OpenClaw first:"
    echo "  curl -fsSL https://openclaw.ai/install.sh | bash"
    exit 1
fi

echo "✅ OpenClaw found: $(openclaw --version)"
echo ""

# Create necessary directories
echo "📁 Creating directories..."
mkdir -p "$WORKSPACE/memory/wellness"
mkdir -p "$WORKSPACE/lab/logs"
mkdir -p "$WORKSPACE/lab/traces"
mkdir -p "$WORKSPACE/lab/agents"
mkdir -p "$WORKSPACE/friday-wiki/wiki/agents"
mkdir -p "$WORKSPACE/friday-wiki/wiki/skills"
mkdir -p "$WORKSPACE/friday-wiki/wiki/concepts"
mkdir -p "$WORKSPACE/friday-wiki/examples"
mkdir -p "$WORKSPACE/friday-wiki/output/answers"
mkdir -p "$WORKSPACE/friday-wiki/output/slides"
mkdir -p "$WORKSPACE/friday-wiki/output/charts"
mkdir -p "$WORKSPACE/tasks"
echo "✅ Directories created"
echo ""

# Copy template files if they don't exist
echo "📄 Checking template files..."

TEMPLATE_FILES=(
    "SOUL.md"
    "USER.md"
    "IDENTITY.md"
    "AGENTS.md"
    "HEARTBEAT.md"
    "TOOLS.md"
)

for file in "${TEMPLATE_FILES[@]}"; do
    if [ ! -f "$WORKSPACE/$file" ]; then
        echo "   Copying $file..."
        cp "$file" "$WORKSPACE/" 2>/dev/null || true
    fi
done

echo "✅ Template files checked"
echo ""

# Create today's memory file
TODAY=$(date +%Y-%m-%d)
if [ ! -f "$WORKSPACE/memory/$TODAY.md" ]; then
    echo "📝 Creating today's memory file..."
    cat > "$WORKSPACE/memory/$TODAY.md" << EOF
# Memory Log — $TODAY

**Generated:** $(date '+%Y-%m-%d %H:%M:%S')

---

## Friday Bootstrap

- [x] Workspace initialized
- [x] Template files copied
- [ ] User configuration (edit USER.md)
- [ ] API keys configured (edit TOOLS.md)
- [ ] First run complete

---

## Notes

*Add notes here throughout the day*

---

*Generated by Friday Bootstrap*
EOF
    echo "✅ Memory file created: $WORKSPACE/memory/$TODAY.md"
else
    echo "✅ Memory file exists: $WORKSPACE/memory/$TODAY.md"
fi
echo ""

# Create tasks/todo.md if it doesn't exist
if [ ! -f "$WORKSPACE/tasks/todo.md" ]; then
    echo "📋 Creating tasks/todo.md..."
    cat > "$WORKSPACE/tasks/todo.md" << 'EOF'
# 📋 Tasks — Todo

**Last Updated:** [Date]

---

## Active Tasks

- [ ] Configure USER.md with your information
- [ ] Add API keys to TOOLS.md
- [ ] Test basic commands
- [ ] Set up cron jobs
- [ ] Run first wellness check-in

---

## Completed

- [x] Friday bootstrap complete

---

## Lessons Learned

*Add lessons here after completing tasks*

---

*Friday Task Manager*
EOF
    echo "✅ Tasks file created"
else
    echo "✅ Tasks file exists"
fi
echo ""

# Create HEARTBEAT.md if it doesn't exist
if [ ! -f "$WORKSPACE/HEARTBEAT.md" ]; then
    echo "💓 Creating HEARTBEAT.md..."
    cat > "$WORKSPACE/HEARTBEAT.md" << 'EOF'
# HEARTBEAT.md - Friday Background Tasks

### 🔄 Every 4-8 Hours
- **Emergency Mode Check:** Verify internet, tokens, services
- **Storm Check:** Check for severe weather alerts
- **Security Watch:** Check for P0/P1 security tasks
- **Notification Digest:** Send batched notifications

### 🌅 Daily Morning (08:30)
- **Log Review:** Analyze last 24h logs
- **Morning Brief:** Generate daily briefing

### 🌙 Daily Evening (22:00)
- **Evening Brief:** Summarize today's activity

### 🌓 Quiet Hours (23:00 - 08:00)
- Stay silent unless critical alert
- Use time for background maintenance

### ☘️ Rule of Engagement
- If nothing is urgent, reply `HEARTBEAT_OK`
- Only interrupt for critical tasks requiring human intervention

---

*Friday Heartbeat System*
EOF
    echo "✅ HEARTBEAT.md created"
else
    echo "✅ HEARTBEAT.md exists"
fi
echo ""

# Set permissions
echo "🔐 Setting permissions..."
chmod +x "$WORKSPACE/lab/"*.py 2>/dev/null || true
chmod +x "$WORKSPACE/bootstrap.sh" 2>/dev/null || true
echo "✅ Permissions set"
echo ""

# Summary
echo "======================================================================="
echo "  ✅ Friday Bootstrap Complete!"
echo "======================================================================="
echo ""
echo "📁 Workspace: $WORKSPACE"
echo ""
echo "🎯 Next Steps:"
echo ""
echo "1. Edit USER.md with your information"
echo "   code $WORKSPACE/USER.md"
echo ""
echo "2. Add API keys to TOOLS.md"
echo "   code $WORKSPACE/TOOLS.md"
echo ""
echo "3. Start OpenClaw"
echo "   openclaw start"
echo ""
echo "4. Test Friday"
echo "   python3 $WORKSPACE/lab/wellness_tracker.py --checkin morning"
echo ""
echo "📚 Documentation:"
echo "   - README.md — Main documentation"
echo "   - docs/SETUP.md — Complete setup guide"
echo "   - SOUL.md — Friday's personality"
echo ""
echo "🤝 Get Help:"
echo "   - Discord: https://discord.com/invite/clawd"
echo "   - Docs: https://docs.openclaw.ai"
echo ""
echo "🎉 Friday is ready to help!"
echo ""
echo "======================================================================="
